### ISSUE TITLE
Make GROUP_NAME validation more strict

### ISSUE THREAD

**Issue by denismakogon** [mattlord/Docker-InnoDB-Cluster#10]
Following command would not fail
```
docker run --name=mysqlgr1 --hostname=mysqlgr1 --network=grnet -e MYSQL_ROOT_PASSWORD=root -e BOOTSTRAP=1 -e GROUP_NAME="test" -itd mattalord/innodb-cluster
```
But `GROUP_NAME` **must** be UUID4 only. Non-empty string doesn't fail boostrap, but should be.

**Comment by mattlord** [comment]
Solved with this patch:
https://github.com/mattlord/Docker-InnoDB-Cluster/commit/d2e3f1b1bb7f8547281675cd5fa660e019e04b8c

Example:
docker run --name=mysqlgr1 --hostname=mysqlgr1 --network=grnet -e MYSQL_ROOT_PASSWORD=root -e BOOTSTRAP=1 -e GROUP_NAME="test1" -itd mattalord/innodb-cluster && docker logs mysqlgr1
67cf6d567da67e6bd768bfda6b3ac55a565ee918309393e98aa1f731abee3e74
info: Bootstrapping Group Replication cluster using --group_replication_group_name=test1
  You will need to specify GROUP_NAME=test1 if you want to add another node to this cluster
error: Specified GROUP_NAME is not a valid UUID

Closing the issue. 

Thanks!
