### ISSUE TITLE
Router provisioning fails silently if replication group members table is empty

### ISSUE THREAD

**Issue by denismakogon** [mattlord/Docker-InnoDB-Cluster#11]
Router provisioning fails silently if replication group members table is empty.
1. Create 3 nodes with the invalid group name.
2. Try to create router.
3. Run `docker ps -a`(router instance process exited)
4. Check route logs:
```
Setting up a new router instance...
```

**Comment by mattlord** [comment]
Unfortunately the mysqlrouter --bootstrap operation provides no output in these cases as nothing really failed. It's just a 0 node cluster. It's a valid problem though, but not in this container. 

Unless I'm misunderstanding something here? Please feel free to re-open if I missed something.

Thanks!
