### ISSUE TITLE
Small bug in setup_cluster.bat file, with port mapping

### ISSUE THREAD

**Issue by rcampuz** [mattlord/Docker-InnoDB-Cluster#14]
Hi Mattlord,

In the **file setup_cluster.bat** when you run the containers you are mapping the external port 339X (where X = 1, 2 and 3) to the same number, when it should be mapped to port 3306 inside the container.

For example, in **line 7** we can see:
`docker run --rm --name=mysqlgr1 --hostname=mysqlgr1 --network=grnet -p 3391:3391 -e MYSQL_ROOT_PASSWORD=root -e BOOTSTRAP=1 -e GROUP_NAME="92bb4382-3bd1-11e7-a919-92ebcb67fe33" -itd mattalord/innodb-cluster`

i.e.
`-p 3391:3391`

where it should be
`-p 3391:3306`

to my humble opinion.

The same would apply to **lines 11 and 15**.

Not sure if this small mistake happened also in other files, as I am testing it just on windows.

Thank you for this great bed to test and play with innoDB cluster.

**Comment by mattlord** [comment]
Corrected: https://github.com/mattlord/Docker-InnoDB-Cluster/commit/d7cae8975671a5b00750eaa9b0e7f140c705a0ca

Thank you for the input! Please let me know if you have any issues with the batch file.  I haven't actually tested it on Windows. :)

**Comment by rcampuz** [comment]
Thank you, now it works great!
